name: 'Use existing build'
description: 'Check repository using clang-tidy - use existing build'
author: 'Bettina Riedl'
branding:
  icon: check-circle
  color: gray-dark
inputs:
  scandir:
    description: 'Scan directory'
    required: false
    default: '.'
  builddir:
    description: 'Build directory'
    required: false
    default: 'build'
  excludedirs:
    description: 'Exclude directories'
    required: false
    default: ''
  extensions:
    description: 'File extensions to include in check'
    required: false
    default: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
runs:
  using: 'composite'
  steps:
    - name: 'Run clang-tidy using existing build'
      shell: bash
      run: python3 action-clang-tidy/run-clang-tidy.py '${{inputs.scandir}}' '${{inputs.builddir}}' '${{inputs.excludedirs}}' '${{inputs.extensions}}'
